### ISSUE TITLE
Error with recurring all-day dates

### ISSUE THREAD

**Issue by HerHde** [HerHde/ical2mail#1]
When I'm trying to parse a file which has recurring full-day events the following error occurs:
```python
Traceback (most recent call last):
  File "ical2mail.py", line 260, in <module>
    main()
  File "ical2mail.py", line 247, in main
    events += parse_ics(url)
  File "ical2mail.py", line 101, in parse_ics
    for dtstart_rec in rule.between(DATE_MIN - timedelta(microseconds=1), DATE_MAX):
  File "/[...]/ical2mail/venv/lib/python3.6/site-packages/dateutil/rrule.py", line 290, in between
    for i in gen:
  File "/[...]/ical2mail/venv/lib/python3.6/site-packages/dateutil/rrule.py", line 861, in _iter
    if until and res > until:
TypeError: can't compare offset-naive and offset-aware datetimes
```
It may be related to dateutil/dateutil#348, but further investigation is necessary.

**Comment by HerHde** [comment]
Found the problem:
The event that crashed the script has the following rrule:

    RRULE:FREQ=WEEKLY;UNTIL=20160125

where the `UNTIL` has no timezone and is therefore offset-naive. Changing it to 

    RRULE:FREQ=WEEKLY;UNTIL=20160125T000000Z

solves the crash.
